package com.example.util

object AppStrings {

    fun get(key: String, language: AppLanguage): String {
        val isEn = language == AppLanguage.EN
        return when (key) {
            // Navigation
            "nav_today" -> if (isEn) "TODAY" else "HEUTE"
            "nav_routines" -> if (isEn) "ROUTINES" else "ROUTINEN"
            "nav_stats" -> if (isEn) "STATS" else "STATS"
            "nav_settings" -> if (isEn) "SETTINGS" else "EINSTELLUNGEN"

            // TodayScreen
            "today_header" -> "DAILY"
            "streak_title" -> if (isEn) "DAILY STREAK" else "TÄGLICHE STREAK"
            "streak_days_suffix" -> if (isEn) "Days in a row" else "Tage in Folge"
            "streak_secured" -> if (isEn) "SECURED" else "GESICHERT"
            "streak_open" -> if (isEn) "OPEN" else "OFFEN"
            "streak_secured_hint" -> if (isEn) "Streak secured! Great work today." else "Streak gesichert! Starke Leistung heute."
            "streak_open_hint" -> if (isEn) "Complete all habits to keep your streak alive" else "Erledige alle Habits, um deine Streak zu sichern"
            "cat_all" -> if (isEn) "ALL" else "ALLE"
            "cat_supplements" -> "SUPPLEMENTS"
            "cat_health" -> if (isEn) "HEALTH" else "GESUNDHEIT"
            "cat_focus" -> if (isEn) "FOCUS" else "FOKUS"
            "cat_workout" -> if (isEn) "WORKOUT" else "SPORT"
            "cat_routine" -> "ROUTINE"
            "habits_title" -> if (isEn) "HABITS" else "AUFGABEN"
            "all_done_title" -> if (isEn) "ALL DONE!" else "ALLES ERLEDIGT!"
            "all_done_subtitle" -> if (isEn) "You completed all habits for today." else "Du hast alle Aufgaben für heute abgeschlossen."
            "no_habits_title" -> if (isEn) "NO HABITS" else "KEINE AUFGABEN"
            "no_habits_subtitle" -> if (isEn) "Tap [+] to create your first habit." else "Tippe auf [+] um eine Gewohnheit hinzuzufügen."
            "add_habit" -> if (isEn) "New Habit" else "Neue Aufgabe"
            "progress_completed_of" -> if (isEn) "%d OF %d COMPLETED" else "%d VON %d ERLEDIGT"
            "progress_percent" -> if (isEn) "%d%% PROGRESS" else "%d%% FORTSCHRITT"
            "streak_badge_days" -> if (isEn) "%d DAYS STREAK" else "%d TAGE STREAK"

            // Notification Permission Card
            "perm_title" -> if (isEn) "ENABLE NOTIFICATIONS" else "ERINNERUNGEN AKTIVIEREN"
            "perm_desc" -> if (isEn) "Allow notifications to receive timely alerts for your daily habits." else "Benachrichtigungen erlauben, um pünktlich an noch offene Aufgaben erinnert zu werden."
            "perm_allow" -> if (isEn) "ALLOW" else "ERLAUBEN"

            // RoutinesScreen
            "routines_header" -> if (isEn) "ROUTINES" else "ROUTINEN"
            "routines_subtitle" -> if (isEn) "All recurring daily habits" else "Alle wiederkehrenden täglichen Aufgaben"
            "active_badge" -> if (isEn) "ACTIVE" else "AKTIV"
            "paused_badge" -> if (isEn) "PAUSED" else "PAUSIERT"
            "dismiss_hint" -> if (isEn) "Dismiss" else "Ausblenden"
            "routines_info" -> if (isEn) {
                "Every day at midnight, your habits reset for the new day. Your streak history is permanently saved."
            } else {
                "Jeden Tag um Mitternacht werden deine Aufgaben automatisch als offen markiert. Deine Historie bleibt erhalten."
            }
            "no_routines_title" -> if (isEn) "NO ROUTINES YET" else "KEINE ROUTINEN DEFINIERT"
            "no_routines_subtitle" -> if (isEn) "Tap [+] to create your first routine." else "Tippe auf [+] um deine erste Routine anzulegen."
            "goal_label" -> if (isEn) "GOAL" else "ZIEL"
            "edit_label" -> if (isEn) "Edit" else "Bearbeiten"
            "new_routine" -> if (isEn) "New Routine" else "Neue Routine"

            // StatsScreen
            "stats_header" -> if (isEn) "STATISTICS" else "STATISTIK"
            "stats_subtitle" -> if (isEn) "Progress, streak & history" else "Fortschritt, Streak & Historie"
            "stats_tab_overall" -> if (isEn) "OVERALL" else "ÜBERSICHT"
            "stats_tab_habits" -> if (isEn) "BY HABIT" else "PRO GEWOHNHEIT"
            "current_streak" -> if (isEn) "CURRENT" else "AKTUELL"
            "best_streak" -> if (isEn) "RECORD" else "REKORD"
            "longest_streak_label" -> if (isEn) "Longest streak" else "Bester Streak"
            "day_single" -> if (isEn) "Day in a row" else "Tag in Folge"
            "days_plural" -> if (isEn) "Days in a row" else "Tage in Folge"
            "rate_label" -> if (isEn) "COMPLETION RATE" else "QUOTE"
            "active_days_subtext" -> if (isEn) "%d of %d days active" else "%d von %d Tagen aktiv"
            "total_days" -> if (isEn) "TOTAL DAYS" else "GESAMTTAGE"
            "total_days_subtext" -> if (isEn) "Days with completions" else "Tage mit Erledigungen"
            "milestones_header" -> if (isEn) "STREAK MILESTONES" else "STREAK-MEILENSTEINE"
            "milestone_reached" -> if (isEn) "REACHED" else "ERREICHT"
            "milestone_left" -> if (isEn) "%d days left" else "Noch %d Tage"
            "month_overview" -> if (isEn) "MONTHLY OVERVIEW" else "MONATS-ÜBERSICHT"
            "month_overview_sub" -> if (isEn) "%s • %d of %d days" else "%s • %d von %d Tagen"
            "history_title" -> if (isEn) "STREAK HISTORY" else "VERLAUFS-HISTORIE"

            // Individual Habit Stats
            "habit_stats_header" -> if (isEn) "HABIT STATISTICS" else "EINZELSTATISTIKEN"
            "habit_stats_subtitle" -> if (isEn) "Detailed breakdown per habit" else "Detaillierte Analyse pro Gewohnheit"
            "select_habit_hint" -> if (isEn) "SELECT HABIT" else "GEWOHNHEIT WÄHLEN"
            "habit_streak_current" -> if (isEn) "CURRENT STREAK" else "AKTUELLE STREAK"
            "habit_streak_best" -> if (isEn) "RECORD STREAK" else "REKORD STREAK"
            "habit_completion_rate" -> if (isEn) "SUCCESS RATE" else "ERFOLGSQUOTE"
            "habit_total_done" -> if (isEn) "TOTAL COMPLETED" else "GESAMT ERLEDIGT"
            "habit_total_volume" -> if (isEn) "TOTAL VOLUME" else "GESAMT-MENGE"
            "habit_last_7_days" -> if (isEn) "LAST 7 DAYS ACTIVITY" else "AKTIVITÄT LETZTE 7 TAGE"
            "habit_month_matrix" -> if (isEn) "HABIT CALENDAR" else "GEWOHNHEITSKALENDER"
            "habit_all_comparison" -> if (isEn) "ALL HABITS COMPARISON" else "ALLE GEWOHNHEITEN IM VERGLEICH"
            "habit_status_secured" -> if (isEn) "DONE TODAY" else "HEUTE ERLEDIGT"
            "habit_status_open" -> if (isEn) "OPEN TODAY" else "HEUTE OFFEN"
            "habit_status_rest" -> if (isEn) "REST DAY" else "HEUTE FREI"
            "habit_milestones_title" -> if (isEn) "HABIT MILESTONES" else "MEILENSTEINE DIESER GEWOHNHEIT"
            "habit_no_habits" -> if (isEn) "NO HABITS DEFINED" else "KEINE GEWOHNHEITEN DEFINIERT"
            "habit_no_habits_desc" -> if (isEn) "Create habits in Today or Routines to view detailed individual stats." else "Lege im Tab 'Heute' oder 'Routinen' Gewohnheiten an, um individuelle Statistiken zu sehen."
            "habit_overview_card_title" -> if (isEn) "HABITS AT A GLANCE" else "GEWOHNHEITEN IM ÜBERBLICK"
            "habit_overview_card_sub" -> if (isEn) "Streaks & completion rates" else "Streaks & Erfolgsquoten"
            "habit_view_details_btn" -> if (isEn) "VIEW HABIT DETAILS →" else "DETAILS PRO GEWOHNHEIT →"
            "habit_times_completed_format" -> if (isEn) "%d× completed" else "%d× abgeschlossen"

            // Milestones
            "ms_3_title" -> if (isEn) "3 DAYS" else "3 TAGE"
            "ms_3_desc" -> if (isEn) "First Step" else "Erster Anlauf"
            "ms_7_title" -> if (isEn) "7 DAYS" else "7 TAGE"
            "ms_7_desc" -> if (isEn) "1 Week Discipline" else "1 Woche Disziplin"
            "ms_14_title" -> if (isEn) "14 DAYS" else "14 TAGE"
            "ms_14_desc" -> if (isEn) "Solid Routine" else "Feste Routine"
            "ms_30_title" -> if (isEn) "30 DAYS" else "30 TAGE"
            "ms_30_desc" -> if (isEn) "Month Master" else "Monatsmeister"
            "ms_100_title" -> if (isEn) "100 DAYS" else "100 TAGE"
            "ms_100_desc" -> if (isEn) "Lifestyle" else "Lebensstil"

            // TaskEditDialog
            "dialog_new_task" -> if (isEn) "NEW HABIT" else "NEUE AUFGABE"
            "dialog_edit_task" -> if (isEn) "EDIT HABIT" else "AUFGABE BEARBEITEN"
            "task_name_label" -> if (isEn) "Habit name" else "Aufgabenname"
            "task_name_placeholder" -> if (isEn) "e.g. 100 Pushups" else "z.B. Vitamin D3 nehmen"
            "category_label" -> if (isEn) "CATEGORY" else "KATEGORIE"
            "frequency_label" -> if (isEn) "SCHEDULE / FREQUENCY" else "RHYTHMUS & HÄUFIGKEIT"
            "freq_daily" -> if (isEn) "DAILY" else "TÄGLICH"
            "freq_weekly" -> if (isEn) "WEEKLY" else "WÖCHENTLICH"
            "freq_weekdays" -> if (isEn) "WEEKDAYS" else "WOCHENTAGE"
            "weekly_target_title" -> if (isEn) "TARGET PER WEEK" else "ZIEL PRO WOCHE"
            "times_per_week" -> if (isEn) "%d× PER WEEK" else "%d× PRO WOCHE"
            "select_days_hint" -> if (isEn) "Select active weekdays" else "Wähle aktive Wochentage"
            "weekly_progress_tag" -> if (isEn) "%d/%d THIS WEEK" else "%d/%d DIESE WOCHE"
            "weekly_goal_met_tag" -> if (isEn) "GOAL MET (%d/%d)" else "ZIEL ERREICHT (%d/%d)"
            "not_due_today_tag" -> if (isEn) "REST DAY" else "HEUTE FREI"
            "not_due_today_section" -> if (isEn) "NOT DUE TODAY" else "HEUTE NICHT FÄLLIG"
            "not_due_today_sub" -> if (isEn) "Scheduled for other days" else "Für andere Tage eingeplant"
            "not_due_toast" -> if (isEn) "Only scheduled for: %s" else "Nur an folgenden Tagen geplant: %s"
            "not_due_cant_check" -> if (isEn) "Cannot check off today" else "Heute nicht abhakbar"
            "past_day_readonly_toast" -> if (isEn) "Past days cannot be modified" else "Vergangene Tage können nicht nachträglich bearbeitet werden"
            "past_day_tag" -> if (isEn) "PAST DAY • VIEW ONLY" else "VERGANGENER TAG • NUR ANSICHT"
            "no_habits_due_today_title" -> if (isEn) "NO HABITS DUE TODAY" else "HEUTE KEINE AUFGABEN FÄLLIG"
            "no_habits_due_today_sub" -> if (isEn) "No tasks scheduled for today. Enjoy your day!" else "Für heute sind keine Aufgaben geplant. Genieße den Tag!"
            "habit_type_label" -> if (isEn) "HABIT TYPE" else "HABIT-TYP"
            "type_simple" -> if (isEn) "SIMPLE (CHECK)" else "EINFACH (CHECK)"
            "type_counter" -> if (isEn) "COUNTER (GOAL)" else "ZÄHLER (ZIEL)"
            "target_amount_label" -> if (isEn) "Target quantity" else "Zielmenge"
            "target_unit_label" -> if (isEn) "Unit" else "Einheit"
            "reminder_label" -> if (isEn) "DAILY REMINDER" else "TÄGLICHE ERINNERUNG"
            "reminder_set_at" -> if (isEn) "Notification at %s" else "Benachrichtigung um %s Uhr"
            "set_time_button" -> if (isEn) "SET TIME" else "UHRZEIT EINSTELLEN"
            "save_task" -> if (isEn) "SAVE HABIT" else "AUFGABE SPEICHERN"
            "save_changes" -> if (isEn) "SAVE CHANGES" else "ÄNDERUNGEN SPEICHERN"
            "delete" -> if (isEn) "Delete" else "Löschen"

            // SettingsScreen
            "settings_header" -> if (isEn) "SETTINGS" else "EINSTELLUNGEN"
            "settings_subtitle" -> if (isEn) "SYSTEM & PREFERENCES" else "SYSTEM & PERSONALISIERUNG"
            "general_reminder_title" -> if (isEn) "DAILY REMINDER" else "TÄGLICHE ERINNERUNG"
            "general_reminder_desc" -> if (isEn) "Alert if habits are incomplete" else "Benachrichtigt bei offenen Habits"
            "time_label" -> if (isEn) "TIME" else "UHRZEIT"
            "test_notification_btn" -> if (isEn) "SEND TEST NOTIFICATION" else "TEST-BENACHRICHTIGUNG SENDEN"
            "test_notification_sent" -> if (isEn) "Test notification sent!" else "Test-Benachrichtigung gesendet!"
            "reminder_enabled_toast" -> if (isEn) "Reminder scheduled for" else "Erinnerung aktiviert für"
            "accent_title" -> if (isEn) "ACCENT COLOR" else "AKZENTFARBE"
            "accent_desc" -> if (isEn) "Color for streaks, buttons & indicators" else "Farbe für Streaks, Buttons & Indikatoren"
            "typography_title" -> if (isEn) "TYPOGRAPHY" else "SCHRIFTARTEN"
            "typography_desc" -> if (isEn) "Customize headings & body text" else "Überschriften & Textkörper anpassen"
            "headings_label" -> if (isEn) "HEADINGS" else "ÜBERSCHRIFTEN"
            "body_label" -> if (isEn) "BODY TEXT & NUMBERS (GEIST)" else "TEXTKÖRPER & ZAHLEN (GEIST)"
            "language_title" -> if (isEn) "LANGUAGE" else "SPRACHE"
            "language_desc" -> if (isEn) "Choose interface language" else "App-Oberfläche auf Deutsch oder Englisch"
            "settings_haptics_title" -> if (isEn) "HAPTIC FEEDBACK" else "VIBRATIONS-FEEDBACK"
            "settings_haptics_desc" -> if (isEn) "Tactile vibration when completing tasks & finishing day" else "Vibration beim Abhaken & Tages-Abschluss"
            "settings_animation_title" -> if (isEn) "COMPLETION EFFECT" else "ABSCHLUSS-EFFEKT"
            "settings_animation_desc" -> if (isEn) "Dot-Matrix animation when 100% habits are done" else "Dot-Matrix-Effekt bei 100% erledigten Aufgaben"
            "settings_test_effect_btn" -> if (isEn) "PREVIEW COMPLETION EFFECT" else "ABSCHLUSS-EFFEKT TESTEN"

            // Celebration
            "celebration_title" -> if (isEn) "ALL DONE!" else "ALLES ERLEDIGT!"
            "celebration_streak_secured" -> if (isEn) "STREAK SECURED • %d DAYS" else "STREAK GESICHERT • %d TAGE"
            "celebration_tap_to_dismiss" -> if (isEn) "TAP TO DISMISS" else "TIPPEN ZUM SCHLIESSEN"

            // Notifications
            "notif_task_reminder_title" -> if (isEn) "DAILY • REMINDER" else "DAILY • ERINNERUNG"
            "notif_task_reminder_body" -> if (isEn) "%s is still pending" else "%s ist noch offen"
            "notif_mark_done" -> if (isEn) "✓ Done" else "✓ Erledigen"
            "notif_general_title" -> if (isEn) "DAILY • INCOMPLETE HABITS" else "DAILY • OFFENE HABITS"
            "notif_general_body" -> if (isEn) "%d of %d habits left today. Keep your streak alive!" else "Noch %d von %d Gewohnheiten heute offen. Sichere deine Streak!"
            "notif_test_title" -> if (isEn) "DAILY • TEST REMINDER" else "DAILY • TEST-ERINNERUNG"
            "notif_test_body" -> if (isEn) "Notifications are active! You have habits to complete." else "Benachrichtigungen sind aktiv! Du hast noch Habits offen."
            "notif_snooze_10m" -> if (isEn) "10m" else "10 Min"
            "notif_snooze_30m" -> if (isEn) "30m" else "30 Min"
            "notif_snooze_60m" -> if (isEn) "60m" else "60 Min"
            "notif_snooze_toast" -> if (isEn) "Reminder snoozed for %d minutes" else "Erinnerung um %d Minuten verschoben"
            "notif_snoozed_indicator" -> if (isEn) "Snoozed" else "Schlummernd"
            "settings_snooze_info" -> if (isEn) "Snooze directly in notifications (10 / 30 / 60 min.)" else "Schlummern direkt in der Benachrichtigung (10 / 30 / 60 Min.)"

            // Widgets
            "widget_no_habits" -> if (isEn) "NO HABITS" else "KEINE AUFGABEN"
            "widget_day_streak" -> if (isEn) "DAY STREAK" else "TAG STREAK"
            "widget_days_streak" -> if (isEn) "DAYS STREAK" else "TAGE STREAK"
            "widget_today_all_done" -> if (isEn) "TODAY: ALL DONE!" else "HEUTE: ALLES ERLEDIGT!"
            "widget_today_status" -> if (isEn) "TODAY: %d/%d" else "HEUTE: %d/%d"
            "widget_zero_habits" -> if (isEn) "0 HABITS" else "0 AUFGABEN"
            "widget_progress_title" -> if (isEn) "DAILY PROGRESS" else "TÄGLICHER FORTSCHRITT"
            "widget_progress_completed" -> if (isEn) "%d OF %d COMPLETED" else "%d VON %d ERLEDIGT"
            "widget_progress_left_singular" -> if (isEn) "1 HABIT LEFT" else "1 AUFGABE OFFEN"
            "widget_progress_left_plural" -> if (isEn) "%d HABITS LEFT" else "%d AUFGABEN OFFEN"
            "widget_progress_all_done" -> if (isEn) "ALL DONE • STREAK SECURED" else "ALLES ERLEDIGT • STREAK GESICHERT"
            "widget_progress_no_habits" -> if (isEn) "NO HABITS TODAY" else "KEINE AUFGABEN HEUTE"

            else -> key
        }
    }
}
